version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "ecogrid-container"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-0e5b8a5c8f9d2e1a3", "subnet-0f6c9b6d9a0e3f2b4"]
            SecurityGroups: ["sg-0a1b2c3d4e5f6g7h8"]
            AssignPublicIp: "ENABLED"

Hooks:
  - BeforeInstall:
      - location: scripts/pre_deployment_check.sh
        timeout: 300
  - AfterInstall:
      - location: scripts/post_deployment_validation.sh
        timeout: 300
  - ApplicationStart:
      - location: scripts/health_check.sh
        timeout: 300
  - ApplicationStop:
      - location: scripts/cleanup.sh
        timeout: 300
