version: 0.2

phases:
  build:
    commands:
      - echo Deploy started on `date`
      - echo Triggering CodeDeploy blue-green deployment...
      - |
        aws deploy create-deployment \
          --application-name ecogrid-app \
          --deployment-group-name ecogrid-bg-dg \
          --s3-location bucket=codepipeline-us-east-1-442042546183,key=ecogrid-3stage-pipeline/BuildArtif,bundleType=zip \
          --deployment-config-name CodeDeployDefault.ECSBlueGreenCanary10Percent5Minutes \
          --description "Blue-Green deployment triggered by pipeline"
      - echo Deployment completed successfully
